server:
  port: 8000

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xueshen?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
#    jdbc:mysql://localhost:3306/mybatis_plus?
    #useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置mybatis
mybatis:
  mapper-locations:  classpath:com/dh/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#sql语句日志的打印
logging:
  level:
    com.dh.m_plus.mapper: debug
